FROM maven:3.5-jdk-8-slim
EXPOSE 8080

WORKDIR /usr/src/app
COPY pom.xml .
COPY exec-module1/pom.xml ./exec-module1/
COPY exec-module2/pom.xml ./exec-module2/
RUN ["/usr/local/bin/mvn-entrypoint.sh", "mvn", "verify", "--fail-never"]
COPY . .
RUN ["mvn", "package"]

CMD ["java", "-jar", "exec-module2/target/exec-multi-module-module2-1.0.one-jar.jar"]